# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
- group: secrets
- name: DB_PASSWORD
  value: $(DB_PASSWORD)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- script: |
    FILE_PATH = '$(System.DefaultWorkingDirectory)/testdata.json'
    PLACEHOLDER = 'dbpassword'
    DB_PASSWORD=$(DB_PASSWORD)
    sed -i "s/${PLACEHOLDER}/${DB_PASSWORD}/g" ${FILE_PATH}
    

